---
# defaults file for hugo_deploy
# domain and user settings

domain_name: wuweb.westeurope.cloudapp.azure.com
certbot_email: democritushygge@gmail.com 
deploy_user: azureuser
web_root: /var/www/html/my-blog

